spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
logging.level:
  org.hibernate.SQL: debug
---
jwt:
  secret: umc-6th.focus.up.2024=secret=key
---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f71c6a4557473c996f92460f623c01e5
            client-secret: 9wVgT4NXGqlGZf4rXjPnnLSswy7vy53a
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
            client-name: kakao

          naver:
            client-id: 4nfuo2Z3pPZY9U__xMW_
            client-secret: $QcqZYUm3F7
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization_grant_type: authorization_code
            scope:
            client-name: Naver
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response