name: Deploy to AWS EC2

# 이 워크플로는 main 브랜치에 push되거나 pull request가 있을 때 실행됩니다.
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # 저장소의 코드를 읽는 권한

    steps:
      # 저장소 체크아웃
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Java JDK 17 설치
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application.yml
        run: |
          rm -rf ./src/main/resources
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > ./src/main/resources/application.yml
        shell: bash

      # gradlew 실행 권한 부여
      - name: Grant permission for gradlew
        run: chmod +x gradlew

      # 프로젝트 빌드
      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      # docker hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 스프링 부트 어플리케이션 docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/focusup .
          docker push ${{ secrets.DOCKER_USERNAME }}/focusup

      # EC2 인스턴스에 배포
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master  # EC2 인스턴스에 SSH로 접근
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 인스턴스의 호스트 이름
          username: ${{ secrets.EC2_USERNAME }}  # EC2 인스턴스의 사용자 이름
          key: ${{ secrets.EC2_SSH_KEY }}  # SSH 접속에 필요한 비밀 키
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/shortdari:latest
            docker stop web || true
            docker rm web || true
            docker run -d --name focusup_server --network docker_network -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/focusup:latest
